const users = [
  {
    id: 1,
    firstName: "Sonni",
    lastName: "Cluer",
    email: "scluer0@woothemes.com",
    gender: "Female",
    age: 15,
  },
  {
    id: 2,
    firstName: "Norris",
    lastName: "Headrick",
    email: "nheadrick1@ow.ly",
    gender: "Male",
    age: 8,
  },
  {
    id: 3,
    firstName: "Noelani",
    lastName: "Ferie",
    email: "nferie2@mapy.cz",
    gender: "Female",
    age: 66,
  },
  {
    id: 4,
    firstName: "Marylin",
    lastName: "Lyford",
    email: "mlyford3@redcross.org",
    gender: "Female",
    age: 80,
  },
  {
    id: 5,
    firstName: "Phillip",
    lastName: "Duchesne",
    email: "pduchesne4@latimes.com",
    gender: "Male",
    age: 32,
  },
  {
    id: 6,
    firstName: "Gibb",
    lastName: "Spiring",
    email: "gspiring5@jiathis.com",
    gender: "Male",
    age: 51,
  },
  {
    id: 7,
    firstName: "Gnni",
    lastName: "Wragge",
    email: "gwragge6@webnode.com",
    gender: "Female",
    age: 1,
  },
  {
    id: 8,
    firstName: "Carmella",
    lastName: "Nation",
    email: "cnation7@altervista.org",
    gender: "Female",
    age: 42,
  },
  {
    id: 9,
    firstName: "Josie",
    lastName: "Rawet",
    email: "jrawet8@foxnews.com",
    gender: "Female",
    age: 33,
  },
  {
    id: 10,
    firstName: "Rawley",
    lastName: "Denisevich",
    email: "rdenisevich9@census.gov",
    gender: "Male",
    age: 19,
  },
  {
    id: 11,
    firstName: "Charley",
    lastName: "Windibank",
    email: "cwindibanka@telegraph.co.uk",
    gender: "Male",
    age: 16,
  },
  {
    id: 12,
    firstName: "Alma",
    lastName: "Magowan",
    email: "amagowanb@nps.gov",
    gender: "Female",
    age: 62,
  },
  {
    id: 13,
    firstName: "Hermy",
    lastName: "Newlin",
    email: "hnewlinc@omniture.com",
    gender: "Male",
    age: 87,
  },
  {
    id: 14,
    firstName: "Garrett",
    lastName: "Harback",
    email: "gharbackd@soundcloud.com",
    gender: "Male",
    age: 62,
  },
  {
    id: 15,
    firstName: "Guthry",
    lastName: "Dewfall",
    email: "gdewfalle@washington.edu",
    gender: "Male",
    age: 69,
  },
  {
    id: 16,
    firstName: "Leopold",
    lastName: "Gornal",
    email: "lgornalf@ocn.ne.jp",
    gender: "Male",
    age: 96,
  },
  {
    id: 17,
    firstName: "Lishe",
    lastName: "Bamblett",
    email: "lbamblettg@arizona.edu",
    gender: "Female",
    age: 71,
  },
  {
    id: 18,
    firstName: "Olympia",
    lastName: "Pawellek",
    email: "opawellekh@webnode.com",
    gender: "Female",
    age: 75,
  },
  {
    id: 19,
    firstName: "Hillery",
    lastName: "Creese",
    email: "hcreesei@tinyurl.com",
    gender: "Male",
    age: 64,
  },
  {
    id: 20,
    firstName: "Noelani",
    lastName: "Schuchmacher",
    email: "nschuchmacherj@psu.edu",
    gender: "Female",
    age: 4,
  },
  {
    id: 21,
    firstName: "Kevin",
    lastName: "Pieche",
    email: "kpiechek@yahoo.com",
    gender: "Male",
    age: 23,
  },
  {
    id: 22,
    firstName: "Sim",
    lastName: "Attwell",
    email: "sattwelll@ezinearticles.com",
    gender: "Male",
    age: 67,
  },
  {
    id: 23,
    firstName: "Filip",
    lastName: "Maulkin",
    email: "fmaulkinm@artisteer.com",
    gender: "Male",
    age: 18,
  },
  {
    id: 24,
    firstName: "Lolly",
    lastName: "Wrinch",
    email: "lwrinchn@ed.gov",
    gender: "Female",
    age: 9,
  },
  {
    id: 25,
    firstName: "Stanislaus",
    lastName: "Behrend",
    email: "sbehrendo@tiny.cc",
    gender: "Male",
    age: 52,
  },
  {
    id: 26,
    firstName: "Mikkel",
    lastName: "Douse",
    email: "mdousep@whitehouse.gov",
    gender: "Male",
    age: 95,
  },
  {
    id: 27,
    firstName: "Cahra",
    lastName: "Llewhellin",
    email: "cllewhellinq@comsenz.com",
    gender: "Female",
    age: 53,
  },
  {
    id: 28,
    firstName: "Tracie",
    lastName: "Denkin",
    email: "tdenkinr@ovh.net",
    gender: "Male",
    age: 19,
  },
  {
    id: 29,
    firstName: "Lyon",
    lastName: "Riseam",
    email: "lriseams@mozilla.org",
    gender: "Male",
    age: 1,
  },
  {
    id: 30,
    firstName: "Petrina",
    lastName: "Forsyth",
    email: "pforsytht@blinklist.com",
    gender: "Female",
    age: 58,
  },
];

module.exports = { users };
